#=================================
# Global Master Config Properties
#=================================


# Eureka Instance
eureka:
  client:
    serviceUrl:
      defaultZone: http://discoveryserver:8761/eureka
      metadata-map:
        user.name: admin
        user.password: admin


# Zipkin Instance
spring:
  zipkin:
    baseUrl: http://zipkinserver:9411
  cloud:
    config:
      override-system-properties: false
