#=================================
# Global Master Config Properties
#=================================


# Eureka Instance
eureka:
  client:
    serviceUrl:
      defaultZone: http://discoveryserver:8761/eureka


# Zipkin Instance
spring:
  zipkin:
    baseUrl: http://zipkinserver:9411
  cloud:
    config:
      override-system-properties: false
